max_farming_crops = 280  # Last verified as of 2.48 Giftmas Event
max_farming_value = 10000  # Last verified as of 2.21 The Fixening
# Base 1 + 10 from Grimoire + 30 from Legend Talents: Extended Database
max_land_rank_level = 41

crop_dict = {
    # Basic
    0: {"Name": "Apple", "Image": "apple-crop"},
    1: {"Name": "Orange"},
    2: {"Name": "Lemon"},
    3: {"Name": "Pear"},
    4: {"Name": "Strawberry"},
    5: {"Name": "Bananas"},
    6: {"Name": "Blueberry"},
    7: {"Name": "Brown Grapes"},
    8: {"Name": "Red Pear"},
    9: {"Name": "Pineapple"},
    10: {"Name": "Lime"},
    11: {"Name": "Raspberry"},
    12: {"Name": "Fig"},
    13: {"Name": "Peach"},
    14: {"Name": "Purple Grapes"},
    15: {"Name": "Yellow Pear"},
    16: {"Name": "Watermelon"},
    17: {"Name": "Green Grapes"},
    18: {"Name": "Dragon Fruit"},
    19: {"Name": "Mango"},
    20: {"Name": "Gold Blueberry"},
    # Earthy
    21: {"Name": "Carrot"},
    22: {"Name": "Potato"},
    23: {"Name": "Beat"},
    24: {"Name": "Tomato"},
    25: {"Name": "Artichoke"},
    26: {"Name": "Roma Tomato"},
    27: {"Name": "Butternut Squash"},
    28: {"Name": "Avocado"},
    29: {"Name": "Red Pepper"},
    30: {"Name": "Broccoli"},
    31: {"Name": "Radish"},
    32: {"Name": "Coconut"},
    33: {"Name": "Sliced Tomato"},
    34: {"Name": "Cashew"},
    35: {"Name": "Turnip"},
    36: {"Name": "Coffee Bean"},
    37: {"Name": "Pumpkin"},
    38: {"Name": "Sliced Cucumber"},
    39: {"Name": "Eggplant", "Image": "eggplant-crop"},
    40: {"Name": "Lettuce"},
    41: {"Name": "Garlic"},
    42: {"Name": "Green Beans"},
    43: {"Name": "Bell Pepper"},
    44: {"Name": "Corn", "Image": "corn-crop"},
    45: {"Name": "Gold Sliced Tomato"},
    # Bulbo
    46: {"Name": "Daisy"},
    47: {"Name": "Flour"},
    48: {"Name": "Stargazer Lily"},
    49: {"Name": "Rose"},
    50: {"Name": "Sunflower"},
    51: {"Name": "Blue Daisy"},
    52: {"Name": "Red Rose"},
    53: {"Name": "Tulip"},
    54: {"Name": "Pink Daisy"},
    55: {"Name": "Cauliflower"},
    56: {"Name": "Cape Marguerite Daisy"},
    57: {"Name": "Papua Black Orchid"},
    58: {"Name": "Muffin"},
    59: {"Name": "Black Rose"},
    60: {"Name": "Golden Tulip"},
    # Sushi
    61: {"Name": "Sushi Crop 1"},
    62: {"Name": "Sushi Crop 2"},
    63: {"Name": "Sushi Crop 3"},
    64: {"Name": "Sushi Crop 4"},
    65: {"Name": "Sushi Crop 5"},
    66: {"Name": "Sushi Crop 6"},
    67: {"Name": "Sushi Crop 7"},
    68: {"Name": "Sushi Crop 8"},
    69: {"Name": "Sushi Crop 9"},
    70: {"Name": "Sushi Crop 10"},
    71: {"Name": "Sushi Crop 11"},
    72: {"Name": "Sushi Crop 12"},
    73: {"Name": "Sushi Crop 13"},
    74: {"Name": "Sushi Crop 14"},
    75: {"Name": "Sushi Crop 15"},
    76: {"Name": "Sushi Crop 16"},
    77: {"Name": "Sushi Crop 17"},
    78: {"Name": "Sushi Crop 18"},
    79: {"Name": "Sushi Crop 19"},
    80: {"Name": "Sushi Crop 20"},
    81: {"Name": "Sushi Crop 21"},
    82: {"Name": "Sushi Crop 22"},
    83: {"Name": "Sushi Crop 23"},
    # Mushie
    84: {"Name": "Mushroom 1"},
    85: {"Name": "Mushroom 2"},
    86: {"Name": "Mushroom 3"},
    87: {"Name": "Mushroom 4"},
    88: {"Name": "Mushroom 5"},
    89: {"Name": "Mushroom 6"},
    90: {"Name": "Mushroom 7"},
    91: {"Name": "Mushroom 8"},
    92: {"Name": "Mushroom 9"},
    93: {"Name": "Mushroom 10"},
    94: {"Name": "Mushroom 11"},
    95: {"Name": "Mushroom 12"},
    96: {"Name": "Mushroom 13"},
    97: {"Name": "Mushroom 14"},
    98: {"Name": "Mushroom 15"},
    99: {"Name": "Mushroom 16"},
    100: {"Name": "Mushroom 17"},
    101: {"Name": "Mushroom 18"},
    102: {"Name": "Mushroom 19"},
    103: {"Name": "Mushroom 20"},
    104: {"Name": "Mushroom 21"},
    105: {"Name": "Mushroom 22"},
    106: {"Name": "Mushroom 23"},
    # Glassy
    # Normal Glassy
    107: {"Name": "Glassy Bananas"},
    108: {"Name": "Glassy Mango"},
    109: {"Name": "Glassy Mushroom"},
    110: {"Name": "Glassy Maki"},
    111: {"Name": "Glassy Broccoli"},
    112: {"Name": "Glassy Carrot"},
    113: {"Name": "Glassy Tomato"},
    114: {"Name": "Glassy Watermelon"},
    115: {"Name": "Glassy Shrimp"},
    116: {"Name": "Glassy Rose"},
    117: {"Name": "Glassy Lettuce"},
    118: {"Name": "Glassy Onigiri"},
    119: {"Name": "Glassy Corn"},
    # Red Glassy
    120: {"Name": "Red Glassy Bananas"},
    121: {"Name": "Red Glassy Mango"},
    122: {"Name": "Red Glassy Broccoli"},
    123: {"Name": "Red Glassy Carrot"},
    124: {"Name": "Red Glassy Tomato"},
    125: {"Name": "Red Glassy Watermelon"},
    126: {"Name": "Red Glassy Shrimp"},
    127: {"Name": "Red Glassy Rose"},
    128: {"Name": "Red Glassy Onigiri"},
    129: {"Name": "Red Glassy Corn"},
    # Green Glassy
    130: {"Name": "Green Glassy Bananas"},
    131: {"Name": "Green Glassy Mango"},
    132: {"Name": "Green Glassy Broccoli"},
    133: {"Name": "Green Glassy Carrot"},
    134: {"Name": "Green Glassy Tomato"},
    135: {"Name": "Green Glassy Watermelon"},
    136: {"Name": "Green Glassy Shrimp"},
    137: {"Name": "Green Glassy Rose"},
    138: {"Name": "Green Glassy Onigiri"},
    139: {"Name": "Green Glassy Corn"},
    # White Glassy
    140: {"Name": "White Glassy Bananas"},
    141: {"Name": "White Glassy Mango"},
    142: {"Name": "White Glassy Broccoli"},
    143: {"Name": "White Glassy Carrot"},
    144: {"Name": "White Glassy Tomato"},
    145: {"Name": "White Glassy Watermelon"},
    146: {"Name": "White Glassy Shrimp"},
    147: {"Name": "White Glassy Rose"},
    148: {"Name": "White Glassy Onigiri"},
    149: {"Name": "White Glassy Corn"},
    # Purple Glassy
    150: {"Name": "Purple Glassy Bananas"},
    151: {"Name": "Purple Glassy Mango"},
    152: {"Name": "Purple Glassy Broccoli"},
    153: {"Name": "Purple Glassy Carrot"},
    154: {"Name": "Purple Glassy Tomato"},
    155: {"Name": "Purple Glassy Watermelon"},
    156: {"Name": "Purple Glassy Shrimp"},
    157: {"Name": "Purple Glassy Rose"},
    158: {"Name": "Purple Glassy Onigiri"},
    159: {"Name": "Purple Glassy Corn"},
    # Yellow Glassy
    160: {"Name": "Yellow Glassy Bananas"},
    161: {"Name": "Yellow Glassy Mango"},
    162: {"Name": "Yellow Glassy Broccoli"},
    163: {"Name": "Yellow Glassy Carrot"},
    164: {"Name": "Yellow Glassy Tomato"},
    165: {"Name": "Yellow Glassy Watermelon"},
    166: {"Name": "Yellow Glassy Shrimp"},
    167: {"Name": "Yellow Glassy Rose"},
    168: {"Name": "Yellow Glassy Onigiri"},
    169: {"Name": "Yellow Glassy Corn"},
    # Blue Glassy
    170: {"Name": "Blue Glassy Bananas"},
    171: {"Name": "Blue Glassy Mango"},
    172: {"Name": "Blue Glassy Broccoli"},
    173: {"Name": "Blue Glassy Carrot"},
    174: {"Name": "Blue Glassy Tomato"},
    175: {"Name": "Blue Glassy Watermelon"},
    176: {"Name": "Blue Glassy Shrimp"},
    177: {"Name": "Blue Glassy Rose"},
    178: {"Name": "Blue Glassy Onigiri"},
    179: {"Name": "Blue Glassy Corn"},
    # T08 Glassy
    180: {"Name": "T08 Glassy Bananas"},
    181: {"Name": "T08 Glassy Mango"},
    182: {"Name": "T08 Glassy Broccoli"},
    183: {"Name": "T08 Glassy Carrot"},
    184: {"Name": "T08 Glassy Tomato"},
    185: {"Name": "T08 Glassy Watermelon"},
    186: {"Name": "T08 Glassy Shrimp"},
    187: {"Name": "T08 Glassy Rose"},
    188: {"Name": "T08 Glassy Onigiri"},
    189: {"Name": "T08 Glassy Corn"},
    # T09 Glassy
    190: {"Name": "T09 Glassy Bananas"},
    191: {"Name": "T09 Glassy Mango"},
    192: {"Name": "T09 Glassy Broccoli"},
    193: {"Name": "T09 Glassy Carrot"},
    194: {"Name": "T09 Glassy Tomato"},
    195: {"Name": "T09 Glassy Watermelon"},
    196: {"Name": "T09 Glassy Shrimp"},
    197: {"Name": "T09 Glassy Rose"},
    198: {"Name": "T09 Glassy Onigiri"},
    199: {"Name": "T09 Glassy Corn"},
    # T10 Glassy
    200: {"Name": "T10 Glassy Bananas"},
    201: {"Name": "T10 Glassy Mango"},
    202: {"Name": "T10 Glassy Broccoli"},
    203: {"Name": "T10 Glassy Carrot"},
    204: {"Name": "T10 Glassy Tomato"},
    205: {"Name": "T10 Glassy Watermelon"},
    206: {"Name": "T10 Glassy Shrimp"},
    207: {"Name": "T10 Glassy Rose"},
    208: {"Name": "T10 Glassy Onigiri"},
    209: {"Name": "T10 Glassy Corn"},
    # T11 Glassy
    210: {"Name": "T11 Glassy Bananas"},
    211: {"Name": "T11 Glassy Mango"},
    212: {"Name": "T11 Glassy Broccoli"},
    213: {"Name": "T11 Glassy Carrot"},
    214: {"Name": "T11 Glassy Tomato"},
    215: {"Name": "T11 Glassy Watermelon"},
    216: {"Name": "T11 Glassy Shrimp"},
    217: {"Name": "T11 Glassy Rose"},
    218: {"Name": "T11 Glassy Onigiri"},
    219: {"Name": "T11 Glassy Corn"},
    # T12 Glassy
    220: {"Name": "T12 Glassy Bananas"},
    221: {"Name": "T12 Glassy Mango"},
    222: {"Name": "T12 Glassy Broccoli"},
    223: {"Name": "T12 Glassy Carrot"},
    224: {"Name": "T12 Glassy Tomato"},
    225: {"Name": "T12 Glassy Watermelon"},
    226: {"Name": "T12 Glassy Shrimp"},
    227: {"Name": "T12 Glassy Rose"},
    228: {"Name": "T12 Glassy Onigiri"},
    229: {"Name": "T12 Glassy Corn"},
}

crop_evo_breakpoint_list = [
    # Glassy
    229, 219, 209, 199, 189, 179, 169, 159, 149, 139, 129, 119,
    # Mushie
    106,
    # Sushi
    83,
    # Bulbo
    60,
    # Earthy
    45,
    # Basic
    20
]
