stamp_types: list[str] = ['Combat', 'Skill', 'Misc']

# Last updated in v2.10
unavailable_stamps_list = [
    'Shiny Crab Stamp', 'Gear Stamp', 'SpoOoky Stamp', 'Prayday Stamp',  #Skill
    'Talent I Stamp', 'Talent V Stamp',  #Misc
]
stamp_maxes = {
    #Combat
    "Sword Stamp": 205,
    "Target Stamp": 175,
    "Fist Stamp": 58,
    "Book Stamp": 72,
    "Bullseye Stamp": 110,
    "Buckler Stamp": 182,
    "Avast Yar Stamp": 120,
    "Gilded Axe Stamp": 162,
    "Maxo Slappo Stamp": 140,
    "Dementia Sword Stamp": 200,
    "Void Axe Stamp": 255,
    "Heart Stamp": 170,
    "Shield Stamp": 150,
    "Battleaxe Stamp": 152,
    "Manamoar Stamp": 99,
    "Feather Stamp": 165,
    "Hermes Stamp": 75,
    "Steve Sword": 320,
    "Diamond Axe Stamp": 230,
    "Sashe Sidestamp": 133,
    "Golden Sixes Stamp": 210,
    "Captalist Stats Stamp": 160,
    "Mana Stamp": 165,
    "Longsword Stamp": 136,
    "Agile Stamp": 36,
    "Clover Stamp": 82,
    "Polearm Stamp": 246,
    "Sukka Foo": 220,
    "Blover Stamp": 104,
    "Tripleshot Stamp": 300,
    "Intellectostampo": 168,
    "Stat Wallstreet Stamp": 78,
    "Tomahawk Stamp": 136,
    "Kapow Stamp": 99,
    "Vitality Stamp": 132,
    "Scimitar Stamp": 108,
    "Violence Stamp": 87,
    "Arcane Stamp": 78,
    "Stat Graph Stamp": 95,
    "Blackheart Stamp": 450,
    "Conjocharmo Stamp": 210,
    "Void Sword Stamp": 180,
    #Skill
    "Pickaxe Stamp": 455,
    "Twin Ores Stamp": 120,
    "Smart Dirt Stamp": 165,
    "Alch Go Brrr Stamp": 124,
    "Fishing Rod Stamp": 150,
    "Bag o Heads Stamp": 224,
    "Hidey Box Stamp": 300,
    "Cooked Meal Stamp": 480,
    "Egg Stamp": 480,
    "Divine Stamp": 168,
    "Sneaky Peeky Stamp": 144,
    "Triad Essence Stamp": 136,
    "Hatchet Stamp": 465,
    "Choppin' Bag Stamp": 330,
    "Cool Diggy Tool Stamp": 340,
    "Brainstew Stamps": 155,
    "Fishhead Stamp": 125,
    "Holy Mackerel Stamp": 155,
    "Purp Froge Stamp": 130,
    "Stample Stamp": 124,
    "Flowin Stamp": 82,
    "Spice Stamp": 510,
    "Lab Tube Stamp": 340,
    "Multitool Stamp": 230,
    "Jade Mint Stamp": 150,
    "Dark Triad Essence Stamp": 128,
    "Anvil Zoomer Stamp": 155,
    "Duplogs Stamp": 120,
    "High IQ Lumber Stamp": 165,
    "Drippy Drop Stamp": 160,
    "Catch Net Stamp": 150,
    "Bugsack Stamp": 224,
    "Spikemouth Stamp": 78,
    "Saw Stamp": 90,
    "Ladle Stamp": 320,
    "Sailboat Stamp": 160,
    "Skelefish Stamp": 42,
    "Summoner Stone Stamp": 128,
    "Lil' Mining Baggy Stamp": 310,
    "Matty Bag Stamp": 410,
    "Swag Swingy Tool Stamp": 410,
    "Droplots Stamp": 84,
    "Fly Intel Stamp": 120,
    "Buzz Buzz Stamp": 155,
    "Amplestample Stamp": 68,
    "Banked Pts Stamp": 282,
    "Nest Eggs Stamp": 320,
    "Gamejoy Stamp": 115,
    "Crop Evo Stamp": 85,
    "White Essence Stamp": 136,
    #Misc
    "Questin Stamp": 330,
    "Gold Ball Stamp": 280,
    "Card Stamp": 330,
    "DNA Stamp": 48,
    "Mason Jar Stamp": 160,
    "Potion Stamp": 105,
    "Forge Stamp": 240,
    "Talent II Stamp": 50,
    "Talent S Stamp": 72,
    "Refinery Stamp": 90,
    "Crystallin": 270,
    "Golden Apple Stamp": 136,
    "Vendor Stamp": 150,
    "Talent III Stamp": 66,
    "Multikill Stamp": 112,
    "Atomic Stamp": 144,
    "Arcade Ball Stamp": 310,
    "Ball Timer Stamp": 90,
    "Sigil Stamp": 324,
    "Talent IV Stamp": 56,
    "Biblio Stamp": 66,
    'Cavern Resource Stamp': 240,
    'Study Hall Stamp': 165
}

stamps_exalt_recommendations = [
    'Crystallin', 'Mason Jar Stamp', 'Summoner Stone Stamp', 'Multitool Stamp',
    'Matty Bag Stamp', 'Golden Sixes Stamp', 'Drippy Drop Stamp', 'Gold Ball Stamp',
    'Refinery Stamp', 'Bugsack Stamp', 'Bag o Heads Stamp', "Lil' Mining Baggy Stamp", "Choppin' Bag Stamp",
    'Card Stamp', 'Divine Stamp', 'Golden Apple Stamp', 'Vendor Stamp', 'Study Hall Stamp', 'Cavern Resource Stamp',
]
