nametag_max_level = 5

bonus_image = {
    "Weapon Power": "vault-upgrade-10",
    "STR": "str",
    "AGI": "agi",
    "WIS": "wis",
    "LUK": "luk",
    "Defence": "vault-upgrade-5",
    "Afk Gains Multi": "vault-upgrade-23",
    "Agi": "agi",
    "All Afk Gain": "vault-upgrade-23",
    "All Stats": "ballot-2",
    "Bonus Class Exp": "ballot-15",
    "Bonus Kills": "ballot-5",
    "Bonus Money": "event-shop-9",
    "Boss Damage": "vault-upgrade-22",
    "Class Exp Multi": "meritocracy-27",
    "Crit Chance": "grimoire-upgrade-10",
    "Damage Bonus": "meritocracy-5",
    "Damage Multi": "meritocracy-5",
    "Drop Rate": "vault-upgrade-18",
    "Drop Rate Multi": "vault-upgrade-18",
    "Fight Afk Gain": "vault-upgrade-23",
    "Fishin Efficincy": "ballot-8",
    "Fishing Xp Gain": "vault-upgrade-30",
    "Food Effect": "king-of-food",
    "Luk": "luk",
    "Mining Xp Gain": "mining",
    "Mob Respawn": "vault-upgrade-43",
    "Money": "coins",
    "Multikill Per Tier": "ballot-5",
    "Skill Afk Gain": "vault-upgrade-23",
    "Skill Efficiency": "ballot-7",
    "Skill Exp": "meritocracy-10",
    "Total Damage": "ballot-1",
    "Xp From Monsters": "meritocracy-27",
}
