# Part of spelunk page item name
chapter_name = [
    "The Fear Within",
    "Decay Surrounds",
    "This is Gospel",
    "No Escape",
    "Sunken Plunder",
    "Kelp Primeval",
]
chapter_bonus_img = [
    "spelunking",
    "spelunking",
    "spelunking",
    "placeholder",
    "spelunking",
    "spelunking",
    "spelunking-tool-0",
    "spelunking-amber-0",
    "spelunking-shop-upgrade-4",
    "spelunking-shop-upgrade-5",
    "spelunking-shop-upgrade-6",
    "placeholder",
    "spelunking-shop-upgrade-4",
    "spelunking",
    "spelunking-elixir-0",
    "spelunking-chapter-1",
    "spelunking-shop-upgrade-43",
    "spelunking-amber-0",
    "spelunking-tool-0",
    "placeholder",
    "spelunking-tool-0",
    "spelunking-amber-0",
    "spelunking-shop-upgrade-5",
    "placeholder",
]
